apiVersion: v1
kind: Pod
metadata:
  name: dev
spec:
  volumes:
    - name: es-local-storage
      hostPath: 
        path: /Volumes/workspace/ds/data/elasticsearch
    - name: redis-local-storage
      hostPath: 
        path: /Volumes/workspace/ds/data/redis
        type: Directory
    - name: es-local-config
      hostPath:
        path: /Volumes/workspace/ds/config/elasticsearch/elasticsearch.yml
        type: File
    - name: wwwroot
      hostPath:
        path: /Volumes/workspace/wwwroot
        type: Directory
    - name: nginx-sites-enabled
      hostPath:
        path: /Volumes/workspace/ds/config/nginx/conf.d
        type: Directory
    - name: php73-fpm-conf
      hostPath:
        path: /Volumes/workspace/ds/config/php73-fpm/php.ini
        type: File   
  containers:
    - name: "php73-fpm"
      image: php-fpm:7.3.33
      resources:
        limits:
          cpu: "6000m"
          memory: "5G"
      ports:
        - containerPort: 9000
          hostPort: 9073
      volumeMounts:
        - name: wwwroot
          mountPath: /var/www/
        - name: php73-fpm-conf
          mountPath: /usr/local/etc/php/php.ini
    - name: "nginx"
      image: "nginx"
      resources:
        limits:
          cpu: "500m"
          memory: "1G"
      ports:
        - containerPort: 80
          hostPort: 80
      volumeMounts:
        - name: wwwroot
          mountPath: /var/www/
        - name: nginx-sites-enabled
          mountPath: /etc/nginx/conf.d
    - name: "redis"
      image: redis:latest
      resources:
        limits:
          cpu: "3000m"
          memory: "1G"
      ports:
        - containerPort: 6379
          hostPort: 6379
      volumeMounts:
        - name: redis-local-storage
          mountPath: /data
    - name: es
      image: es:6.7.2
      resources: 
        limits:
          cpu: "2000m"
          memory: "2G"
      ports:
        - containerPort: 9200
          hostPort: 9200
        - containerPort: 9300
          hostPort: 9300
      env:
        - name: ES_JAVA_OPTS
          value:  "-Xmx1g -Xms1g"
        - name: discovery.type
          value: single-node
      volumeMounts:
        - name: es-local-storage
          mountPath: /usr/share/elasticsearch/data
        - name: es-local-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
    - name: eshq
      image: elastichq/elasticsearch-hq
      resources:
        limits:
          cpu: "2000m"
          memory: "500M"
      ports:
        - containerPort: 5000
          hostPort: 9800
    - name: zook1
      image: zookeeper:latest
      ports:
        - containerPort: 2181
          hostPort: 2181
      resources: 
        limits:
          cpu: "2500m"
          memory: "1G"


    
      

    
